[package]
name = "jito-shredstream-client"
version = "0.1.0"
edition = "2024"

[workspace]

[dependencies]
jito-protos = { path = "./jito_protos" }
solana-sdk = "=2.2.1"
solana-client = "=2.2.1"
solana-metrics = "=2.2.1"
solana-net-utils = "=2.2.1"
solana-perf = "=2.2.1"
solana-streamer = "=2.2.1"
solana-ledger = { git = "https://github.com/jito-foundation/jito-solana.git", branch = "eric/v2.2-merkle-recovery", package = "solana-ledger" }
solana-entry = "=2.2.1"
ed25519-dalek = "1.0.1"
anyhow = "1.0"
tokio = { version = "1", features = ["full"] }
bincode = "1.3.3"
serde_json = "1"
chrono = "0.4.31"
tonic = { version = "0.10", features = ["tls", "tls-roots", "tls-webpki-roots"] }
futures = "0.3"
